version: "3.7"

services:

  # toiki_bot:
  #   container_name: toiki_bot
  #   build:
  #     context: bot
  #     dockerfile: Dockerfile.dev
  #   restart: unless-stopped
  #   env_file: bot/.env
  #   volumes:
  #     - ./bot/:/app/dev:Z
  #     - bot_ignore:/app/dev/node_modules

  toiki_backend:
    container_name: toiki_backend
    build:
      context: server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file: server/.env
    volumes:
      - ./server/:/app/dev:Z
      - ignore:/app/dev/node_modules

volumes:
  ignore:
  # bot_ignore:
