name: Test

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Test docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build client
        uses: docker/build-push-action@v2
        with:
          tags: toiki-build
          push: false
          context: ./client
          cache-to: type=inline
          build-args: |
            ARCH=linux/amd64

      - name: Build server
        uses: docker/build-push-action@v2
        with:
          tags: toiki-build
          push: false
          context: ./server
          cache-to: type=inline
