name: Test

on:
  push:
    branches-ignore:
      - "main" # all branches except main

jobs:

  test:
    name: Test docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build common
        uses: docker/build-push-action@v2
        with:
          tags: toiki-common
          push: false
          context: ./common
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-common:latest
          cache-to: type=inline

      - name: Build client
        uses: docker/build-push-action@v2
        with:
          tags: toiki-build
          push: false
          context: ./client
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-build:latest
          cache-to: type=inline
          build-args: |
            VITE_API_URL=${{ secrets.API_URL }}
            COMMON_IMAGE=toiki-common:latest

      - name: Build server
        uses: docker/build-push-action@v2
        with:
          tags: toiki-server
          push: false
          context: ./server
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-backend:latest
          cache-to: type=inline
          build-args: |
            COMMON_IMAGE=toiki-common:latest

      - name: Build bot
        uses: docker/build-push-action@v2
        with:
          tags: toiki-bot
          push: false
          context: ./bot
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-bot:latest
          cache-to: type=inline
          build-args: |
            COMMON_IMAGE=toiki-common:latest
