name: Test, Build & Deploy

on:
  push:
    branches:
      - "feat/restructure"

jobs:

  test:
    name: Test docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build client
        uses: docker/build-push-action@v2
        with:
          tags: toiki-build
          push: false
          context: ./client
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-build:latest
          cache-to: type=inline
          build-args: |
            ARCH=linux/amd64

      - name: Build server
        uses: docker/build-push-action@v2
        with:
          tags: toiki-server
          push: false
          context: ./server
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-backend:latest
          cache-to: type=inline

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build toiki-build
        uses: docker/build-push-action@v2
        with:
          tags: toiki-build,ghcr.io/toiki-org/toiki-build:latest
          push: true
          context: ./client
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-build:latest
          cache-to: type=inline
          build-args: |
            ARCH=linux/amd64

      - name: Build & Publish toiki-nginx
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/toiki-org/toiki-nginx:latest
          push: true
          context: ./nginx
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-nginx:latest
          cache-to: type=inline

      - name: Build & Publish toiki-backend
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/toiki-org/toiki-backend:latest
          push: true
          context: ./server
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-backend:latest
          cache-to: type=inline

      - name: Build & Publish toiki-certbot
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/toiki-org/toiki-front:latest
          push: true
          context: ./server
          cache-from: type=registry,ref=ghcr.io/toiki-org/toiki-certbot:latest
          cache-to: type=inline

  deploy:
    needs: [build]
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Prune old docker images
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: cd toiki && git pull origin feat/restructure
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}

      - name: Docker compose up
        uses: TapTap21/docker-remote-deployment-action@v1.1
        with:
          remote_docker_host: ${{ secrets.USERNAME }}@${{ secrets.HOST }}
          ssh_public_key: ${{ secrets.PUBLIC_KEY }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          args: up -d
          docker_login_user: ${{ github.actor }}
          docker_login_password: ${{ secrets.GITHUB_TOKEN }}
          docker_login_registry: ghcr.io
          stack_file_name: toiki/docker-compose.yml

      - name: Prune old docker images
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: cd toiki && docker system prune -a -f
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
